name: SwiniaPlugin
version: 2.9.3
main: pl.twojnick.piggypet.PiggyPet
api-version: 1.13
authors: [TwojNick]
description: Zaawansowany system osobistej swini dla graczy.

commands:
  swinia:
    description: Glowna komenda do zarzadzania swinia.
    usage: /swinia [follow/usun/unfollow]
    aliases: [swinka, pig]
