name: PiggyPet
version: '2.1'
main: pl.twojnick.piggypet.PiggyPet
api-version: '1.20'
author: TwojNick
description: Zaawansowany plugin na swinie-peta z systemem ucieczki i AFK.

commands:
  swinia:
    description: Glowna komenda pluginu PiggyPet
    aliases: [swinki, pet]
  pomoc:
    description: Pomoc dla pluginu
